@extends('layouts.front')
@section('content')
    <!--textofia banner section start-->
    <section class="textofia-banner textofia-banner4 d-flex justify-content-center align-items-center flex-column">
        <div class="head text-center">
            <h1>News Media Intelligence</h1>
        </div>
        <div class="scroll text-center">
            <p>scroll down to see more details.</p>
            <i class="fa-solid fa-arrow-down-long"></i>
        </div>
    </section>
    <!--textofia banner section end-->

    <!--what is section start-->
    <section class="what-is">
        <div class="what-is-content">
            <div class="row">
                <div class="col-md-6">
                    <div class="head">
                        <h2 class="d-none">What is</h2>
                        <h1 class="d-none">News media Intelligence</h1>
                        <p>The analysis of media content has been central in social sciences, due to the
                            key role that media plays in shaping public opinion. </p><p>This includes the analysis
                            of both traditional news outlets, such as newspapers and broadcast media,
                            and modern social media such as Twitter where content is generated by users.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="what-is-img">
                        <img src="{{ asset('front/images/textofia4.png') }}" alt="textofia4">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--what is section end-->

    <!--key section start-->
    <section class="key">
        <div class="key-content">
            <div class="row">
                <div class="col-md-6">
                    <div class="key-img">
                        <img src="{{ asset('front/images/MacBook-Pro2.png') }}" alt="">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="Key-content-details">
                        <div class="head">
                            <div class="heading">
                                <h2>News Media Intelligence</h2>
                                <h1>Key Features</h1>
                            </div>
                        </div>
                        <div class="key-content">
                            <div class="para">
                                <h6>Detect key entities</h6>
                                <p>Identify named entities such as People, Places and Organisations in news
                                    and cluster news artilces according to them</p>
                            </div>

                            <div class="para">
                                <h6>Detect key topics</h6>
                                <p>Find key topics mentioned in a range of news outlets at any given time</p>
                            </div>

                            <div class="para">
                                <h6>Detect events</h6>
                                <p>An automatic event detection model that can detect events from live streams
                                    of online news articles</p>
                            </div>

                            <div class="para">
                                <h6>Comparison of news outlets</h6>
                                <p>Identify key topics and compare the nature of their coverage across several
                                    news outlets </p>
                            </div>

                            <div class="para">
                                <h6>Modelling reader preferences</h6>
                                <p>Predict reader's preferences based on past searches and recommend news
                                    articles from various topics</p>
                            </div>

                            <div class="para">
                                <h6>Identify trends in sentiment</h6>
                                <p>Identify the sentiment towards key topics in news and how this changes over
                                    time</p>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--key section end-->

    <!--how it work section start-->
    <section class="how-we-do d-none">
        <div class="how-we-do-content">
            <div class="row">
                <div class="col-md-6">
                    <div class="head">
                        <h2>How it works</h2>
                        <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Euismod id.</h1>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="para">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget morbi amet, scelerisque felis.
                            Nascetur eget ultrices facilisi suspendisse quis sit vitae urna. Faucibus pretium nisl ac at
                            lacus ut mattis ornare neque. Leo integer proin sociis dolor, magna. Cras sociis fermentum,
                            sollicitudin sit dolor tellus. Feugiat tempor aliquet tristique lobortis proin.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ac elit neque nunc sapien ultrices
                            pretium semper sed integer. Porttitor in netus cursus leo. Justo, odio consequat convallis
                            aenean sit id netus pulvinar sed. Viverra mattis scelerisque est fermentum condimentum massa
                            neque, at. Non phasellus mattis neque porttitor. Dapibus lorem pellentesque pulvinar vitae.
                            Laoreet dictum morbi ridiculus dui risus. Lorem urna urna adipiscing aliquet integer sagittis
                            purus purus eros. Lorem massa in eu enim vitae sed ac.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--how it work section end-->

    @include('front.includes.testimonials')
    @include('front.includes.newsletter')
@endsection
